name: Setup pre-build environment
description: 

inputs: {}
  # image:
  #   description: Image name
  #   required: true
  # platform:
  #   description: Image platform
  #   required: true
  # variant:
  #   description: Variant tag prefix
  #   required: true

runs:
  using: composite
  steps:
    - name: Maximize build space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        df -h
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Github Container Repo
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: set lower case owner name
      run: |
        echo "REPO_OWNER=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'
    - name: Get Current Date
      id: date
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >>${GITHUB_ENV}
    - name: Inject env variables
      uses: falti/dotenv-action@v1.0.4
      with:
        path: ./env
        export-variables: true
        keys-case: bypass
