name: Build main image

on:
  push:
    branches:
      - master
      - workflow
  workflow_dispatch:

jobs:
  build_jupyter_base:
    runs-on: ubuntu-latest
    steps:
      - name: Set lower case repository name
        # Hint from https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
        run: |
          echo "REPO_OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Download jupyter docker stack
        run: |
          git clone --depth 1 https://github.com/jupyter/docker-stacks.git
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to Github Container Repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with cuda base image
        uses: docker/build-push-action@v5
        with:
          context: docker-stacks/images/docker-stacks-foundation
          push: true
          tags: |
             ghcr.io/${{ env.REPO_OWNER_LC }}/docker-stacks-foundation:cuda
          build-args: |
            ROOT_CONTAINER=nvidia/cuda:12.2.2-runtime-ubuntu20.04
            PYTHON_VERSION=3.10
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build base notebook image
        uses: docker/build-push-action@v5
        with:
          context: docker-stacks/images/base-notebook
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/base-notebook:cuda
          build-args: |
            BASE_CONTAINER=ghcr.io/${{ env.REPO_OWNER_LC }}/docker-stacks-foundation:cuda
          cache-from: type=gha
          cache-to: type=gha,mode=max
