name: Build main image

on:
  push:
    branches:
      - main
      - workflow
  workflow_dispatch:

jobs:
  build_main_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to Github Container Repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lower case repository name
        # Hint from https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
        run: |
          echo "REPO_OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Name conversion between ghcr & dockerhub. Replace - with _
        run: |
          echo "DOCKERHUB_IMAGE_NAME=${IMG/-/_}" >> ${GITHUB_ENV}
        env:
          IMG: "${{ env.IMAGE_NAME }}"
      - name: Build image quantumchem
        uses: docker/build-push-action@v3
        with:
          context: ./quantumchem
          push: false
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/quantumchem
          cache-from: type=gha
          cache-to: type=gha,mode=max
