name: Build the ML chem stack with proprietary dependencies

on:
  push:
    branches:
      - master
      - workflow
    paths:
      - 'mlchem_vp/**'
      - '.github/workflows/build_mlchem_proprietary.yml'
  workflow_dispatch:



jobs:
  ml-chem:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "REPO_OWNER=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Get Current Date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >>${GITHUB_ENV}
      - name: Build base notebook image -- nvhpc, amd64 only
        uses: docker/build-push-action@v5
        with:
          context: mlchem_vp/
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/mlchem_vp:nvhpc
            ghcr.io/${{ env.REPO_OWNER }}/mlchem_vp:nvhpc-${{ env.DATE }}
          build-args: |
            BASE_CONTAINER=ghcr.io/${{ env.REPO_OWNER }}/mlchem:nvhpc
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
