name: Build the mlchem_base image (without python packages)

on:
  push:
    branches:
      - master
      - workflow
    paths:
      - 'base/**'
      - '.github/workflows/build_base.yml'
  workflow_dispatch:


jobs:
  foundation-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "REPO_OWNER=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Inject env variables
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ./env
          export-variables: true
          keys-case: bypass
      - name: Download jupyter docker stack
        run: |
          curdir=$(pwd)
          git clone --depth 1 https://github.com/jupyter/docker-stacks.git
          cd docker-stacks
          git fetch origin ${{ env.JUPYTER_COMMIT_HASH }}
          git checkout ${{ env.JUPYTER_COMMIT_HASH }}
          cd $curdir/docker-stacks/images/docker-stacks-foundation/
          cp $curdir/base/* ./
          cat Dockerfile.part >> Dockerfile
          
      - name: Get Current Date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >>${GITHUB_ENV}

      - name: Check disk space
        run: |
          df -h
      - name: Build with foundation image -- oss stack
        uses: docker/build-push-action@v5
        with:
          context: docker-stacks/images/docker-stacks-foundation
          push: true
          tags: |
             ghcr.io/${{ env.REPO_OWNER }}/mlchem_base:latest
             ghcr.io/${{ env.REPO_OWNER }}/mlchem_base:oss-${{ env.DATE }}-ubuntu${{ env.UBUNTU_VERSION }}
          build-args: |
            ROOT_IMAGE=docker.io/ubuntu:${{ env.UBUNTU_VERSION }}
            PYTHON_VERSION=${{ env.BASE_PY_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  trigger-downstream:
    needs: foundation-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Rebuild downstream images
        run: |
          gh workflow run build_worker.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
