name: Mlchem series image

on:
  push:
    branches:
      - master
      - workflow
    paths:
      - 'mlchem/**'
      - '.github/workflows/build_mlchem.yml'
      - '.github/actions'
  workflow_dispatch:



jobs:
  mlchem-slim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Pre-build setup
        uses: ./.github/actions/pre-build
        with:
          ghcr_secret: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: mlchem/slim
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/mlchem_slim:latest
            ghcr.io/${{ env.REPO_OWNER }}/mlchem_slim:oss-${{ env.DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  mlchem-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Pre-build setup
        uses: ./.github/actions/pre-build
        with:
          ghcr_secret: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: mlchem/main
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:latest
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:cpu
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:cpu-${{ env.DATE }}
          build-args: |
            BASE_IMAGE="ghcr.io//${{ env.REPO_OWNER }}/jupyter_pytorch"
            ARG VARIANT="cpu"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  mlchem-cuda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Pre-build setup
        uses: ./.github/actions/pre-build
        with:
          ghcr_secret: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: mlchem/main
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:cuda
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:cpu-${{ env.DATE }}
          build-args: |
            BASE_IMAGE="ghcr.io//${{ env.REPO_OWNER }}/jupyter_pytorch"
            ARG VARIANT="cuda"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64




  # trigger-downstream:
  #   needs: build-image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Rebuild downstream images
  #       run: |
  #         gh workflow run build_mlchem_proprietary.yml
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
