name: Build the base-notebook stack

on:
  push:
    branches:
      - master
      - workflow
  workflow_dispatch:

env:
  # The environmental variables should be manually updated (?)
  JUPYTER_COMMIT_HASH: "00a67281613254de8a253a292313eb7187c83982"
  NVHPC_VERSION: "23.9"
  CUDA_VERSION: "12.2.2"
  MAJOR_CUDA_VERSION: "12.2"
  UBUNTU_VERSION: "22.04"
  BASE_PY_VERSION: "3.10"

jobs:
  build_jupyter_base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to Github Container Repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lower case repository name
        # Hint from https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
        # If OWNER is MyHOST --> REPO_OWNER_LC=myhost
        run: |
          echo "REPO_OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Download jupyter docker stack
        run: |
          git clone --depth 1 https://github.com/jupyter/docker-stacks.git
          cd docker-stacks
          git fetch origin ${JUPYTER_COMMIT_HASH}
          git checkout ${JUPYTER_COMMIT_HASH}
          cd ..
      - name: Build with cuda base image
        uses: docker/build-push-action@v5
        with:
          context: docker-stacks/images/docker-stacks-foundation
          push: true
          tags: |
             ghcr.io/${{ env.REPO_OWNER_LC }}/docker-stacks-foundation:cuda
          build-args: |
            ROOT_CONTAINER=nvcr.io/nvidia/cuda:${{ env.CUDA_VERSION }}-base-ubuntu20.04
            PYTHON_VERSION=${BASE_PY_VERSION}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      - name: Build base notebook image
        uses: docker/build-push-action@v5
        with:
          context: docker-stacks/images/base-notebook
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/base-notebook:cuda
          build-args: |
            BASE_CONTAINER=ghcr.io/${{ env.REPO_OWNER_LC }}/docker-stacks-foundation:cuda
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
