name: Build ML stack

on:
  push:
    branches:
      - master
      - workflow
  workflow_dispatch:  

jobs:
  build_jupyter_base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to Github Container Repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lower case repository name
        # Hint from https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
        # If OWNER is MyHOST --> REPO_OWNER_LC=myhost
        run: |
          echo "REPO_OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      # - name: Import env file from jupyter-base-image
      #   run: |
      #     awk -F '=' '!/^#/ && !/^$/ {print $1"="$2}' ./jupyter-base-image/env >> $GITHUB_ENV
      - name: Build ml image
        uses: docker/build-push-action@v5
        with:
          context: ml
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/ml:cuda
          build-args: |
            BASE_CONTAINER=ghcr.io/${{ env.REPO_OWNER_LC }}/base-notebook:cuda
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platform }}
