name: Build the ML chem stack

on:
  push:
    branches:
      - master
      - workflow
    paths:
      - 'mlchem/**'
      - '.github/workflows/build_mlchem.yml'
  workflow_dispatch:



jobs:
  ml-chem:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - cuda
          - nvhpc
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker hub Container Repo
        uses: docker/login-action@v3
        with:
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.DOCKER_API_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "REPO_OWNER=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Get Current Date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >>${GITHUB_ENV}
      - name: Build base notebook image -- cuda
        uses: docker/build-push-action@v5
        with:
          context: mlchem/
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:cuda
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:cuda-${{ env.DATE }}
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:latest
            docker.io/${{ env.REPO_OWNER }}/mlchem:cuda
            docker.io/${{ env.REPO_OWNER }}/mlchem:cuda-${{ env.DATE }}
            docker.io/${{ env.REPO_OWNER }}/mlchem:latest
          build-args: |
            BASE_CONTAINER=ghcr.io/${{ env.REPO_OWNER }}/base-notebook:cuda
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
        if: matrix.variant == 'cuda'

      - name: Build base notebook image -- nvhpc
        uses: docker/build-push-action@v5
        with:
          context: mlchem/
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:nvhpc
            ghcr.io/${{ env.REPO_OWNER }}/mlchem:nvhpc-${{ env.DATE }}
            docker.io/${{ env.REPO_OWNER }}/mlchem:nvhpc
            docker.io/${{ env.REPO_OWNER }}/mlchem:nvhpc-${{ env.DATE }}
          build-args: |
            BASE_CONTAINER=ghcr.io/${{ env.REPO_OWNER }}/base-notebook:nvhpc
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
        if: matrix.variant == 'nvhpc'

  trigger-downstream:
    needs: ml-chem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rebuild downstream images
        run: |
          gh workflow run build_mlchem_proprietary.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
